project_id = "xpmmysbhvpjnipuzlecy"

[functions.interview-chat]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.practice-feedback]
verify_jwt = false

[functions.interview-summary]
verify_jwt = false

[functions.generate-passage]
verify_jwt = false

[functions.analyze-speech]
verify_jwt = false
